# ============================================================
# bOOmbOOm.NOW! — Jekyll Configuration
# ============================================================

title: boom boom by hammeley.info
baseurl: ""
url: "https://hammeley.info"

api_url: "https://hmmly-boom.up.railway.app/api"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

