# ============================================================
# bOOmbOOm.NOW! — Jekyll Configuration
# ============================================================

title: boom boom by hammeley.info
baseurl: "/bbn"
url: "https://biffjezos.github.io"

api_url: "https://boom.up.railway.app/api"
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

